[ROCm][release/2.10] Fix skipCUDAIf import error in test_linalg.py
Fixes NameError in test_eig_cuda_complex_eigenvectors where skipCUDAIf
was used but not imported. Change to use skipIf which is already imported.

This fixes the error reported in ROCM-20786:
  NameError: name 'skipCUDAIf' is not defined. Did you mean: 'skipCUDAIfRocm'?

The skipIf decorator is already imported from common_device_type and
provides the same functionality for this conditional skip.

Relates-to: ROCM-20786