[release/2.12] Update composable_kernel submodule with gfx90c support (#3480)
## Motivation

Update CK submodule to include cherrypicked
https://github.com/ROCm/rocm-libraries/pull/9333 commit.

## Technical Details

Resolves below build failure and will unblock torch 2.12 builds for
gfx90c.
```
FAILED: [code=1] caffe2/aten/src/ATen/CMakeFiles/ck_gemm.dir/native/hip/bgemm_kernels/bgemm_kernel_bf16bf16bf16_64_16x16x64_16x16_1x1_8x8x1_8x8x1_1x16x1x4_4_Intrawave_v1.hip.o
/__w/rockrel/rockrel/external-builds/pytorch/pytorch/aten/src/ATen/../../../third_party/composable_kernel/include/ck/utility/amd_buffer_addressing_builtins.hpp:49:48: error: use of undeclared identifier 'CK_BUFFER_RESOURCE_3RD_DWORD'
   49 |     wave_buffer_resource.config(Number<3>{}) = CK_BUFFER_RESOURCE_3RD_DWORD;
4 errors generated when compiling for gfx90c.
```

## Test Plan

1. Compile PyTorch's bundled CK for gfx90c
2. Trigger TheRock Multi-Arch PyTorch build w/fix branch

## Test Result
- Before patch -> Results in same `error: use of undeclared identifier
'CK_BUFFER_RESOURCE_3RD_DWORD'`.
- After patch -> Error is no longer seen - Build passes.
- PyTorch 2.10 build passes
https://github.com/ROCm/TheRock/actions/runs/30103245986

## Submission Checklist

- [ ] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.