[windows][smoke test] Add an option to install cuda if required cuda/cudnn on windows AMI do not match (#177369)
[windows][smoke test] Add an option to install cuda if required cuda/cudnn on windows AMI do not match (#177273)

Followup fix for https://github.com/pytorch/pytorch/issues/167242
After https://github.com/pytorch/pytorch/pull/175547 Windows AMI and intendent version of CUDNN do not match. Hence followup fixes required. With this approach we are flexible to update windows CUDNN without actually updating the Windows AMI. Windows AMI update can be done later.

Fixes failure during test: https://github.com/pytorch/pytorch/actions/runs/22979336872/job/66724249070

```
RuntimeError: cuDNN version incompatibility: PyTorch was compiled  against (9, 19, 0) but found runtime version (9, 10, 2). PyTorch already comes bundled with cuDNN. One option to resolving this error is to ensure PyTorch can find the bundled cuDNN.
```

Please note: The cuda/cudnn version will not be updated if the right version is already installed.

Test Plan: In CI via ciflow/binaries
Pull Request resolved: https://github.com/pytorch/pytorch/pull/177273
Approved by: https://github.com/malfet, https://github.com/albanD

(cherry picked from commit e55da9f31ef3ca0a5e0bb0ba29c6d2a6b1352f52)

Co-authored-by: atalman <atalman@fb.com>